const actionTypes =  Object.freeze({
  MOVE_CHECKER: 'MOVE_CHECKER',
  REMOVE_CHECKER: 'REMOVE_CHECKER',
  TOGGLE_PLAYER: 'TOGGLE_PLAYER',
  CHANGE_ONLINE_TAG: 'CHANGE_ONLINE_TAG',
  CHANGE_STAGE: 'CHANGE_STAGE'
});

export default actionTypes;