const actionTypes =  Object.freeze({
  MOVE_CHECKER: 'MOVE_CHECKER',
  REMOVE_CHECKER: 'REMOVE_CHECKER',
  TOGGLE_PLAYER: 'TOGGLE_PLAYER',
  CHANGE_ONLINE_TAG: 'CHANGE_ONLINE_TAG',
  CHANGE_STAGE: 'CHANGE_STAGE',
  RESET_BOARD: 'RESET_BOARD',
  RESET_CURRENT_PLAYER: 'RESET_CURRENT_PLAYER',
  CHANGE_ROOM_ID: 'CHANGE_ROOM_ID' 
});

export default actionTypes;